export const UNIVERSITIES = [
  'UA – Universidade de Aveiro',
  'UP – Universidade do Porto',
  'ULisboa – Universidade de Lisboa',
  'UC – Universidade de Coimbra',
  'UMinho – Universidade do Minho',
  'NOVA – Universidade Nova de Lisboa',
  'UTAD – Universidade de Trás-os-Montes e Alto Douro',
  'UBI – Universidade da Beira Interior',
  'UAlg – Universidade do Algarve',
  'UÉvora – Universidade de Évora',
  'UAc – Universidade dos Açores',
  'UMa – Universidade da Madeira',
  'IPP – Instituto Politécnico do Porto',
  'IPL – Instituto Politécnico de Lisboa',
  'IPC – Instituto Politécnico de Coimbra',
  'IPLeiria – Instituto Politécnico de Leiria',
  'IPV – Instituto Politécnico de Viseu',
  'IPVC – Instituto Politécnico de Viana do Castelo',
  'IPB – Instituto Politécnico de Bragança',
  'IPCB – Instituto Politécnico de Castelo Branco',
  'IPS – Instituto Politécnico de Setúbal',
  'IPT – Instituto Politécnico de Tomar',
  'IPBeja – Instituto Politécnico de Beja',
  'IPSantarém – Instituto Politécnico de Santarém',
  'IPPortalegre – Instituto Politécnico de Portalegre',
  'IPCA – Instituto Politécnico do Cávado e do Ave',
  'UCP – Universidade Católica Portuguesa',
  'Universidade Lusófona - Lisboa',
  'Universidade Lusófona - Porto',
  'Universidade Lusíada',
  'UPT – Universidade Portucalense',
  'UFP – Universidade Fernando Pessoa',
  'ISMAT – Instituto Superior Manuel Teixeira Gomes',
  'UAL – Universidade Autónoma de Lisboa',
  'Universidade Europeia',
] as const

export const COURSES = [
  'Engenharia Civil',
  'Engenharia de Construção e Reabilitação',
  'Reabilitação de Património',
  'Engenharia Municipal',
  'Engenharia Geotécnica e Geoambientais',
  'Engenharia Geológica',
  'Gestão da Construção',
  'Direção de Obra',
  'Arquitetura',
  'Arquitetura Paisagista',
  'Engenharia do Ambiente',
  'Engenharia Ambiental',
  'Planeamento Regional e Urbano',
  'Ordenamento do Território',
  'Engenharia Mecânica',
  'Engenharia e Gestão Industrial',
  'Engenharia Geográfica',
  'Engenharia Geomática',
  'CTeSP em Condução de Obra e Reabilitação',
  'CTeSP em Modelação BIM e Desenho Técnico',
  'CTeSP em Topografia e Sistemas de Informação Geográfica',
  'CTeSP em Tecnologias da Construção Civil',
] as const

export type University = typeof UNIVERSITIES[number]
export type Course = typeof COURSES[number]
